2016-05-09T03:13:32.236024+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2016-05-09T03:13:32.236025+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-05-09T03:13:32.236026+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-09T03:13:32.236026+00:00 app[web.1]:     self.callable = self.load()
2016-05-09T03:13:32.236027+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-09T03:13:32.236027+00:00 app[web.1]:     return self.load_wsgiapp()
2016-05-09T03:13:32.236028+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2016-05-09T03:13:32.236029+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2016-05-09T03:13:32.236028+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-09T03:13:32.236030+00:00 app[web.1]:     __import__(module)
2016-05-09T03:13:32.236030+00:00 app[web.1]: ImportError: No module named gettingstarted.wsgi
2016-05-09T03:13:32.236118+00:00 app[web.1]: [2016-05-09 03:13:32 +0000] [9] [INFO] Worker exiting (pid: 9)
2016-05-09T03:13:32.264147+00:00 app[web.1]: [2016-05-09 03:13:32 +0000] [10] [INFO] Booting worker with pid: 10
2016-05-09T03:13:32.276718+00:00 app[web.1]: [2016-05-09 03:13:32 +0000] [10] [ERROR] Exception in worker process:
2016-05-09T03:13:32.276727+00:00 app[web.1]: Traceback (most recent call last):
2016-05-09T03:13:32.276728+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2016-05-09T03:13:32.276729+00:00 app[web.1]:     worker.init_process()
2016-05-09T03:13:32.276730+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2016-05-09T03:13:32.276730+00:00 app[web.1]:     self.load_wsgi()
2016-05-09T03:13:32.276731+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2016-05-09T03:13:32.276732+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-05-09T03:13:32.276732+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-09T03:13:32.276733+00:00 app[web.1]:     self.callable = self.load()
2016-05-09T03:13:32.276734+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-09T03:13:32.276735+00:00 app[web.1]:     return self.load_wsgiapp()
2016-05-09T03:13:32.276736+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2016-05-09T03:13:32.276736+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-09T03:13:32.276737+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2016-05-09T03:13:32.276737+00:00 app[web.1]:     __import__(module)
2016-05-09T03:13:32.276738+00:00 app[web.1]: ImportError: No module named gettingstarted.wsgi
2016-05-09T03:13:32.276738+00:00 app[web.1]: Traceback (most recent call last):
2016-05-09T03:13:32.276739+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2016-05-09T03:13:32.276740+00:00 app[web.1]:     worker.init_process()
2016-05-09T03:13:32.276740+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2016-05-09T03:13:32.276741+00:00 app[web.1]:     self.load_wsgi()
2016-05-09T03:13:32.276742+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2016-05-09T03:13:32.276742+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-05-09T03:13:32.276743+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-09T03:13:32.276744+00:00 app[web.1]:     self.callable = self.load()
2016-05-09T03:13:32.276744+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-09T03:13:32.276745+00:00 app[web.1]:     return self.load_wsgiapp()
2016-05-09T03:13:32.276746+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2016-05-09T03:13:32.276747+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2016-05-09T03:13:32.276746+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-09T03:13:32.276748+00:00 app[web.1]:     __import__(module)
2016-05-09T03:13:32.276748+00:00 app[web.1]: ImportError: No module named gettingstarted.wsgi
2016-05-09T03:13:32.276831+00:00 app[web.1]: [2016-05-09 03:13:32 +0000] [10] [INFO] Worker exiting (pid: 10)
2016-05-09T03:13:32.300418+00:00 app[web.1]: [2016-05-09 03:13:32 +0000] [3] [INFO] Shutting down: Master
2016-05-09T03:13:32.300551+00:00 app[web.1]: [2016-05-09 03:13:32 +0000] [3] [INFO] Reason: Worker failed to boot.
2016-05-09T03:13:33.456510+00:00 heroku[web.1]: State changed from starting to crashed
2016-05-09T03:13:33.442956+00:00 heroku[web.1]: Process exited with status 3
2016-05-09T03:15:47.544120+00:00 heroku[slug-compiler]: Slug compilation finished
2016-05-09T03:15:47.544115+00:00 heroku[slug-compiler]: Slug compilation started
2016-05-09T03:15:47.360594+00:00 heroku[api]: Release v10 created by potter1990@gmail.com
2016-05-09T03:15:47.360594+00:00 heroku[api]: Deploy 331d954 by potter1990@gmail.com
2016-05-09T03:15:47.717252+00:00 heroku[web.1]: State changed from crashed to starting
2016-05-09T03:15:51.295374+00:00 heroku[web.1]: Starting process with command `gunicorn AIRPACT_Fire.wsgi --log-file -`
2016-05-09T03:15:53.241159+00:00 app[web.1]: [2016-05-09 03:15:53 +0000] [3] [INFO] Starting gunicorn 19.4.5
2016-05-09T03:15:53.241696+00:00 app[web.1]: [2016-05-09 03:15:53 +0000] [3] [INFO] Listening at: http://0.0.0.0:18261 (3)
2016-05-09T03:15:53.241797+00:00 app[web.1]: [2016-05-09 03:15:53 +0000] [3] [INFO] Using worker: sync
2016-05-09T03:15:53.245973+00:00 app[web.1]: [2016-05-09 03:15:53 +0000] [9] [INFO] Booting worker with pid: 9
2016-05-09T03:15:53.248366+00:00 app[web.1]: [2016-05-09 03:15:53 +0000] [9] [ERROR] Exception in worker process:
2016-05-09T03:15:53.248389+00:00 app[web.1]: Traceback (most recent call last):
2016-05-09T03:15:53.248395+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2016-05-09T03:15:53.248400+00:00 app[web.1]:     worker.init_process()
2016-05-09T03:15:53.248400+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2016-05-09T03:15:53.248401+00:00 app[web.1]:     self.load_wsgi()
2016-05-09T03:15:53.248401+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2016-05-09T03:15:53.248402+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-05-09T03:15:53.248407+00:00 app[web.1]:     self.callable = self.load()
2016-05-09T03:15:53.248406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-09T03:15:53.248407+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-09T03:15:53.248408+00:00 app[web.1]:     return self.load_wsgiapp()
2016-05-09T03:15:53.248408+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2016-05-09T03:15:53.248408+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-09T03:15:53.248409+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2016-05-09T03:15:53.248409+00:00 app[web.1]:     __import__(module)
2016-05-09T03:15:53.248409+00:00 app[web.1]: ImportError: No module named AIRPACT_Fire.wsgi
2016-05-09T03:15:53.248410+00:00 app[web.1]: Traceback (most recent call last):
2016-05-09T03:15:53.248410+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2016-05-09T03:15:53.248411+00:00 app[web.1]:     worker.init_process()
2016-05-09T03:15:53.248411+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2016-05-09T03:15:53.248411+00:00 app[web.1]:     self.load_wsgi()
2016-05-09T03:15:53.248412+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2016-05-09T03:15:53.248412+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-05-09T03:15:53.248412+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-09T03:15:53.248413+00:00 app[web.1]:     self.callable = self.load()
2016-05-09T03:15:53.248413+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-09T03:15:53.248413+00:00 app[web.1]:     return self.load_wsgiapp()
2016-05-09T03:15:53.248414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2016-05-09T03:15:53.248414+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-09T03:15:53.248414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2016-05-09T03:15:53.248415+00:00 app[web.1]:     __import__(module)
2016-05-09T03:15:53.248415+00:00 app[web.1]: ImportError: No module named AIRPACT_Fire.wsgi
2016-05-09T03:15:53.248495+00:00 app[web.1]: [2016-05-09 03:15:53 +0000] [9] [INFO] Worker exiting (pid: 9)
2016-05-09T03:15:53.265439+00:00 app[web.1]: [2016-05-09 03:15:53 +0000] [3] [INFO] Shutting down: Master
2016-05-09T03:15:53.265554+00:00 app[web.1]: [2016-05-09 03:15:53 +0000] [3] [INFO] Reason: Worker failed to boot.
2016-05-09T03:15:53.979771+00:00 heroku[web.1]: State changed from starting to crashed
2016-05-09T03:15:53.966936+00:00 heroku[web.1]: Process exited with status 3
2016-05-09T03:16:00.654174+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=dry-harbor-33710.herokuapp.com request_id=6642be68-0178-4d50-a442-414453c0f201 fwd="76.178.152.115" dyno= connect= service= status=503 bytes=
2016-05-09T03:16:01.024316+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=dry-harbor-33710.herokuapp.com request_id=b2661a0f-c5e7-434f-950a-a923a279ab5e fwd="76.178.152.115" dyno= connect= service= status=503 bytes=
2016-05-09T03:16:13.729331+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=dry-harbor-33710.herokuapp.com request_id=addaa571-b519-40c1-9cc1-f6498064a679 fwd="76.178.152.115" dyno= connect= service= status=503 bytes=
2016-05-09T03:16:14.570079+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=dry-harbor-33710.herokuapp.com request_id=59e0ae1a-013b-4cfe-b824-e9a7aa9796ee fwd="76.178.152.115" dyno= connect= service= status=503 bytes=
2016-05-09T03:17:03.734382+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=dry-harbor-33710.herokuapp.com request_id=3e304d4f-d9f2-456d-9c9d-9729d3481789 fwd="76.178.152.115" dyno= connect= service= status=503 bytes=
2016-05-09T03:17:04.166221+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=dry-harbor-33710.herokuapp.com request_id=726d9972-f8b6-4220-b7fb-e727a2cd04fd fwd="76.178.152.115" dyno= connect= service= status=503 bytes=
2016-05-09T03:21:57.348604+00:00 heroku[web.1]: State changed from crashed to starting
2016-05-09T03:22:01.851954+00:00 heroku[web.1]: Starting process with command `gunicorn AIRPACT_Fire.wsgi --log-file -`
2016-05-09T03:22:04.558706+00:00 app[web.1]: [2016-05-09 03:22:04 +0000] [3] [INFO] Starting gunicorn 19.4.5
2016-05-09T03:22:04.559501+00:00 app[web.1]: [2016-05-09 03:22:04 +0000] [3] [INFO] Listening at: http://0.0.0.0:57168 (3)
2016-05-09T03:22:04.559646+00:00 app[web.1]: [2016-05-09 03:22:04 +0000] [3] [INFO] Using worker: sync
2016-05-09T03:22:04.563750+00:00 app[web.1]: [2016-05-09 03:22:04 +0000] [9] [INFO] Booting worker with pid: 9
2016-05-09T03:22:04.566369+00:00 app[web.1]: [2016-05-09 03:22:04 +0000] [9] [ERROR] Exception in worker process:
2016-05-09T03:22:04.566378+00:00 app[web.1]: Traceback (most recent call last):
2016-05-09T03:22:04.566379+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2016-05-09T03:22:04.566380+00:00 app[web.1]:     worker.init_process()
2016-05-09T03:22:04.566380+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2016-05-09T03:22:04.566381+00:00 app[web.1]:     self.load_wsgi()
2016-05-09T03:22:04.566382+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2016-05-09T03:22:04.566382+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-05-09T03:22:04.566383+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-09T03:22:04.566383+00:00 app[web.1]:     self.callable = self.load()
2016-05-09T03:22:04.566384+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-09T03:22:04.566384+00:00 app[web.1]:     return self.load_wsgiapp()
2016-05-09T03:22:04.566385+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2016-05-09T03:22:04.566386+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-09T03:22:04.566386+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2016-05-09T03:22:04.566387+00:00 app[web.1]:     __import__(module)
2016-05-09T03:22:04.566388+00:00 app[web.1]: ImportError: No module named AIRPACT_Fire.wsgi
2016-05-09T03:22:04.566388+00:00 app[web.1]: Traceback (most recent call last):
2016-05-09T03:22:04.566389+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2016-05-09T03:22:04.566389+00:00 app[web.1]:     worker.init_process()
2016-05-09T03:22:04.566390+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2016-05-09T03:22:04.566391+00:00 app[web.1]:     self.load_wsgi()
2016-05-09T03:22:04.566391+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2016-05-09T03:22:04.566392+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-05-09T03:22:04.566393+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-09T03:22:04.566393+00:00 app[web.1]:     self.callable = self.load()
2016-05-09T03:22:04.566394+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-09T03:22:04.566394+00:00 app[web.1]:     return self.load_wsgiapp()
2016-05-09T03:22:04.566395+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2016-05-09T03:22:04.566396+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-09T03:22:04.566396+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2016-05-09T03:22:04.566397+00:00 app[web.1]:     __import__(module)
2016-05-09T03:22:04.566397+00:00 app[web.1]: ImportError: No module named AIRPACT_Fire.wsgi
2016-05-09T03:22:04.566502+00:00 app[web.1]: [2016-05-09 03:22:04 +0000] [9] [INFO] Worker exiting (pid: 9)
2016-05-09T03:22:04.584846+00:00 app[web.1]: [2016-05-09 03:22:04 +0000] [3] [INFO] Shutting down: Master
2016-05-09T03:22:04.584983+00:00 app[web.1]: [2016-05-09 03:22:04 +0000] [3] [INFO] Reason: Worker failed to boot.
2016-05-09T03:22:05.550701+00:00 heroku[web.1]: State changed from starting to crashed
2016-05-09T03:22:05.567027+00:00 heroku[web.1]: Process exited with status 3
